#关闭防火墙
- name: stop firewalld
  shell: 
         systemctl stop firewalld
#设置selinux
- name: set selinux disabled
  selinux:
        state: disabled
#下载nginx
- name: install nginx
  yum : 
        name: nginx
        state: latest
#开机启动nginx
- name: enable nginx
  shell:
        systemctl enable nginx
#配置nginx负载均衡
- name: config nginx lb server
  template: 
        src: /etc/ansible/roles/nginx_LB/templates/nginx_lb.conf.j2
        dest: /etc/nginx/conf.d/nginx_lb.conf
 #触发器，配置文件修改，触发重启nginx
 # notify: 
 # - restart nginx
#启动nginx
- name: start nginx
  shell:
          systemctl start nginx






