#安装mysql
- name: install mariadb
  yum:
        name: mariadb,mariadb-server
        state: latest
#启动数据库
- name: enable mariadb
  service: 
        name: mariadb
        state: started
- name: start mariadb
  shell: 
        systemctl start mariadb 
#执行脚本创建远程登录管理用户
#将本地脚本copy到remote主机
- name: 
  copy: 
        src: /etc/ansible/roles/mysql_install/files/mysql_remote_user.sh
        dest: ./mysql_remote_user.sh
#远程执行脚本
- name:
  shell:
        chmod +x ./mysql_remote_user.sh
- name:
  shell:
        ./mysql_remote_user.sh  
#重启数据库
- name: restart mariadb
  service:
        name: mariadb
        state: restarted



